---
- name: "基础软件安装"
  yum: name={{item}} state=installed
  with_items:
    - epel-release
    - yum-utils
    - lvm2
    - gcc
    - gcc-c++
    - ipvsadm
    - device-mapper-persistent-data
    - wget
    - net-tools
    - lrzsz 
    - ntpdate
    - etcd
    - keepalived
    - haproxy

- name: "防火墙配置"
  shell: systemctl stop firewalld  && systemctl disable firewalld &&/usr/sbin/iptables -P FORWARD ACCEPT

- name: "swap配置"
  shell: swapoff -a && sed -i 's/.*swap.*/#&/' /etc/fstab
  
- name: "拷贝转发参数配置文件"
  copy: src=k8s.conf dest=/etc/sysctl.d/ mode=0644
  
- name: "转发参数配置"  
  shell: modprobe br_netfilter && sysctl -p /etc/sysctl.d/k8s.conf  

- name: "ipvs参数配置文件"
  copy: src=ipvs.modules dest=/etc/sysconfig/modules/ipvs.modules  mode=0755

- name: "ipvs参数配置"
  shell: bash /etc/sysconfig/modules/ipvs.modules && lsmod | grep -e ip_vs -e nf_conntrack_ipv4
  
- name: "配置selinux"
  shell: sed -i 's/SELINUX=permissive/SELINUX=disabled/' /etc/sysconfig/selinux 

- name: "设置主机名"
  shell: hostnamectl set-hostname {{name}} 

- name: "设置hosts"
  template: src=hosts.j2 dest=/etc/hosts

- name: "dockeryum源导入"
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo      
    
- name: "k8syum源导入"
  copy: src=kubernetes.repo dest=/etc/yum.repos.d/ mode=0644
  
- name: "安装docker"
  shell: yum install docker-ce-18.06.1.ce-3.el7 -y 
    
- name: "安装kubelet"
  yum: name=kubelet-{{ kubeversion }} state=installed
- name: "安装kubeadm"
  yum: name=kubeadm-{{ kubeversion }} state=installed
- name: "安装kubectl"
  yum: name=kubectl-{{ kubeversion }} state=installed
    
- name: "docker启动"
  shell: systemctl enable docker.service && systemctl restart docker  && systemctl enable kubelet &&  systemctl start kubelet && usermod -aG docker $(whoami)

- name: "docker 参数设置"
  shell: sed -i "s@ExecStart=/usr/bin/dockerd@ExecStart=/usr/bin/dockerd -H=0.0.0.0:2375 -H unix:///var/run/docker.sock@g"  /lib/systemd/system/docker.service

- name: "docker 加速设置"
  copy: src=daemon.json dest=/etc/docker/ mode=0644  
  
- name: "ntp同步"
  cron: name='ntpdate' minute="20" job="/usr/sbin/ntpdate time7.aliyun.com"
  notify:
    - restart computer


